# Generated by Django 2.1 on 2018-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='markers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('menu', models.TextField()),
                ('class_id', models.IntegerField()),
                ('name', models.TextField()),
                ('color', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'markers',
            },
        ),
    ]
