# Generated by Django 2.1 on 2018-08-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imagelist',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('thumb_image', models.TextField()),
                ('image', models.TextField()),
                ('labels', models.TextField()),
            ],
        ),
    ]
