# Generated by Django 2.1 on 2018-08-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu_selection',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.TextField()),
                ('menu', models.TextField()),
                ('marker_size', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'menu_selection',
            },
        ),
        migrations.AlterModelOptions(
            name='imagelist',
            options={'verbose_name_plural': 'imagelist'},
        ),
    ]
