# Generated by Django 2.1 on 2019-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0002_auto_20180822_1707'),
    ]

    operations = [
        migrations.CreateModel(
            name='ihclist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('type', models.TextField()),
                ('thumb_image', models.TextField()),
                ('image', models.TextField()),
                ('labels', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'ihclist',
            },
        ),
    ]
