# Generated by Django 2.1 on 2019-07-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagelist', '0003_ihclist'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_selection',
            name='localserver',
            field=models.BooleanField(default=False),
        ),
    ]
