# Generated by Django 2.1 on 2018-08-27 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tcgapatient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.TextField()),
                ('gender', models.TextField()),
                ('birth', models.IntegerField()),
                ('race', models.TextField()),
                ('os', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'tcgapatient',
            },
        ),
    ]
