# Generated by Django 2.1 on 2018-08-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcgalist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tcgapatient',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tcgapatient',
            name='path',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
